server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

spring:
  session:
    store-type: redis
    timeout: 2592000
  application:
    name: yun-picture-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eimy
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v4.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.eimy.yunpicturebackend.controller
